In [1]:
# The basics
import numpy as np
import pandas as pd

# Some plotting
import matplotlib.pyplot as plt
plt.style.use('fivethirtyeight')

import plotly.graph_objects as go
import plotly.express as px

In [2]:
review = pd.read_csv('../data/raw/Reviews.csv')

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.layers import Embedding

In [50]:
docs = review

In [51]:
labels = np.array([1,1,1,1,1,0,0,0,0,0])

In [54]:
vocab_size = 50

In [55]:
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[18, 24], [2, 49], [44, 39], [15, 49], [9], [38], [32, 39], [35, 2], [32, 49], [46, 42, 24, 41]]


In [56]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
print(padded_docs)

[[18 24  0  0]
 [ 2 49  0  0]
 [44 39  0  0]
 [15 49  0  0]
 [ 9  0  0  0]
 [38  0  0  0]
 [32 39  0  0]
 [35  2  0  0]
 [32 49  0  0]
 [46 42 24 41]]


In [57]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))

In [58]:
# compile the model
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

In [59]:
# summarize the model
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, 4, 8)              400       
Total params: 400
Trainable params: 400
Non-trainable params: 0
_________________________________________________________________


In [60]:
model.fit(padded_docs)

Train on 10 samples
10/10 [==============================] - 0s 2ms/sample


IndexError: list index out of range